export const PARENT_STATE_SET = "PARENT_STATE_SET";
export const PARENT_STATE_RESET = "PARENT_STATE_RESET";
export const FIRST_CHILD_STATE_SET = "FIRST_CHILD_STATE_SET";
export const FIRST_CHILD_STATE_RESET = "FIRST_CHILD_STATE_RESET";
export const SECOND_CHILD_STATE_SET = "SECOND_CHILD_STATE_SET";
export const SECOND_CHILD_STATE_RESET = "SECOND_CHILD_STATE_RESET";
